channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - pip:
      - azure-ai-ml==1.15.0
      - azureml-mlflow==1.53.0
      - mlflow==2.8.1
      - scikit-learn==1.0.2
      - pandas==1.5.3
      - pyarrow==10.0.0
      - joblib==1.2.0
      - matplotlib==3.6.3
      - scipy==1.9.3